/** @format */

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavbarComponent from "@/navbar/components/navbar.component";
import ProviderComponent from "@/components/provider.component";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ProviderComponent>
          <header>
            <NavbarComponent />
          </header>
          {children}{" "}
        </ProviderComponent>
      </body>
    </html>
  );
}
